<a href="https://colab.research.google.com/github/abhishekmali9191/Data-Analytics-/blob/main/Home_DA_practice_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
my_list=[1,2,3,4]
my_array=np.array([1,23,45,56,78])
type(my_list)

list

In [ ]:
type(my_array)

numpy.ndarray

In [ ]:
my_array

array([ 1, 23, 45, 56, 78])

In [ ]:
np.array(my_list)

array([1, 2, 3, 4])

In [ ]:
np.array(my_array)

array([ 1, 23, 45, 56, 78])

In [ ]:
mat= np.array([[11,122,33],[55,44,66],[99,77,88]])
type(mat)
mat

array([[ 11, 122,  33],
       [ 55,  44,  66],
       [ 99,  77,  88]])

In [ ]:
mat.shape


(3, 3)

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,20,2)    #Start , Stop(not included), Step

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
#array of zeros and onces
x=np.zeros(5)
x.dtype

dtype('float64')

In [ ]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.linspace(1,10,9)     #evenly divide the numbers and give us the result in that range
np.linspace(0,100,5)    #here we give the start, stop, and number of division not the steps
                        #like we give in arange , and also the stop is included in the range


array([  0.,  25.,  50.,  75., 100.])

In [ ]:
np.random.rand(2)

array([0.26366772, 0.77384394])

In [ ]:
np.random.seed(2)          #here the random.seed function is used to give the same value wherever
                           #we give the call to random.randint function on any machine
np.random.randint(10,100)  #if given only one value then it by default consider the first value as 0

50

In [ ]:
np.random.randn(2)
np.random.randn(2,5)

array([[-0.69384098,  0.3630556 ,  2.28365863, -0.25503797,  0.55424383],
       [ 0.963662  ,  2.6460672 , -0.04386375, -0.96561968,  0.87866389]])

In [ ]:
np.random.seed(5)
np.random.rand(3)

array([0.22199317, 0.87073231, 0.20671916])

In [ ]:
arr=np.random.randint(0,101,25)
arr

array([67, 65, 55,  3, 91, 78, 27, 29, 33, 89, 85,  7, 16, 94, 14, 90, 31,
        9, 38, 47, 16,  5, 34, 45, 59])

In [ ]:
arr.reshape(5,5)

array([[67, 65, 55,  3, 91],
       [78, 27, 29, 33, 89],
       [85,  7, 16, 94, 14],
       [90, 31,  9, 38, 47],
       [16,  5, 34, 45, 59]])

In [ ]:
arr.max()

94

In [ ]:
arr.min()

3

In [ ]:
arr.argmax()

13

In [ ]:
arr.argmin()

3

In [ ]:
arr= np.arange(1,12)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr[8]

9

In [ ]:
arr[0:5]   #slicing int the array

array([1, 2, 3, 4, 5])

In [ ]:
arr[-1]

11

In [ ]:
arr[-2]

10

In [ ]:
arr[-3]

9

In [ ]:
arr[-10]

2

In [ ]:
arr[-3:-1]

array([ 9, 10])

In [ ]:
arr[2:-1]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[3:6]=100      #This concept is called as broadcasting in the arr
arr

array([  1,   2,   3, 100, 100, 100,   7,   8,   9,  10,  11])

In [ ]:
arr2=arr
arr2

array([  1,   2,   3, 100, 100, 100,   7,   8,   9,  10,  11])

In [ ]:
copy_arr=arr
copy_arr

array([  1,   2,   3, 100, 100, 100,   7,   8,   9,  10,  11])

In [ ]:
copy_arr[6:8]=50
copy_arr

array([  1,   2,   3, 100, 100, 100,  50,  50,   9,  10,  11])

In [ ]:
arr                    # So changes made in the copied array is also saved in the original array

array([  1,   2,   3, 100, 100, 100,  50,  50,   9,  10,  11])

In [ ]:
arr2                  # it aslo get saved in all the arrays that are copied from the original array

array([  1,   2,   3, 100, 100, 100,  50,  50,   9,  10,  11])

In [ ]:
arr3=arr.copy()       # to prevent this updation of the array we have to explicitly copy the array using copy function
arr3

array([  1,  25,  25, 100, 100, 100,  50,  50,   9,  10,  11])

In [ ]:
arr[1:3]=20
arr

array([  1,  20,  20, 100, 100, 100,  50,  50,   9,  10,  11])

In [ ]:
copy_arr
arr2

array([  1,  20,  20, 100, 100, 100,  50,  50,   9,  10,  11])

In [ ]:
arr3

array([  1,  25,  25, 100, 100, 100,  50,  50,   9,  10,  11])

In [ ]:
#conditional selections
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr+arr           #element wise addition
                 # Always remember the array size should be same to perform this arithmetic operations

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr*arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
arr1 = np.arange(0,10)
arr/arr1    # while dividing by zero it will raise the warning but print inf(infinity) and continue the exectuion

<ipython-input-164-d8004111ef5f>:2: RuntimeWarning: divide by zero encountered in divide
  arr/arr1    # while dividing by zero it will raise the warning but print inf(infinity) and continue the exectuion


array([       inf, 2.        , 1.5       , 1.33333333, 1.25      ,
       1.2       , 1.16666667, 1.14285714, 1.125     , 1.11111111])

In [ ]:
arr1/arr1    # and if we divide zero/zero then it will give nan

<ipython-input-165-f958b1cc4b79>:1: RuntimeWarning: invalid value encountered in divide
  arr1/arr1


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
arr**3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [ ]:
#Universal function
np.sqrt(arr**2)
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [ ]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [ ]:
#Summary statistics
arr.sum()
arr.mean()
arr.max()
arr.argmax()
arr.min()
arr.argmin()
arr.var()    # Gives Variance along the axis
arr.std()    # Standard Deviation

2.8722813232690143

In [ ]:
#2-D Array
arr = np.random.randint(1,100,12)
arr

array([ 8, 87, 17, 65,  9, 91, 45, 38, 95, 76,  6, 23])

In [ ]:
arr.reshape(3,4)

array([[ 8, 87, 17, 65],
       [ 9, 91, 45, 38],
       [95, 76,  6, 23]])

In [ ]:
arr.shape

(12,)

In [ ]:
arr=np.array([[25, 14, 32], [33, 77, 45],  [6, 15, 48], [95, 83,  1]])
arr

array([[25, 14, 32],
       [33, 77, 45],
       [ 6, 15, 48],
       [95, 83,  1]])

In [ ]:
arr.shape

(4, 3)

In [ ]:
arr.sum()

474

In [ ]:
arr.sum(axis=0)    # Gives sum column wise

array([159, 189, 126])

In [ ]:
arr.sum(axis=1)    # Give sum row wise

array([ 71, 155,  69, 179])